name: salesman_app
description: "Bawaskar Salesman ERP Flutter app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  geolocator: ^13.0.2
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/walletApp/