/// The English source text for every translatable label in the salesman app.
///
/// This map is the fallback shown when a translation has not arrived yet, and
/// it is also what gets posted to `POST /translations/sync` so the server can
/// translate and store the strings. Keys are `group.name`; the group is what
/// the admin Website Translations screen filters on, so keep it meaningful.
const Map<String, String> kAppStringsEn = <String, String>{
  // --- advances ----------------------------------------------------------------
  'advances.advances_and_loans': 'Advances & Loans',
  'advances.over_emis': 'over {n} EMIs of {amount}',
  'advances.recovered': 'Recovered',
  'advances.recovered_amount': 'Recovered {amount}',
  'advances.repaid': 'Repaid',
  'advances.request_a_salary_advance_or_a': 'Request a salary advance or a loan, and track how much has been recovered from your salary.',
  'advances.request_advance': 'Request Advance',
  'advances.request_submitted_for_approval': 'Request submitted for approval.',
  'advances.sanctioned': 'Sanctioned',

  // --- announcements -----------------------------------------------------------
  'announcements.circulars': 'Circulars',
  'announcements.company_announcements_circulars_and_notices_published': 'Company announcements, circulars and notices published for field staff.',
  'announcements.company_notices': 'Company Notices',
  'announcements.notices': 'Notices',
  'announcements.official': 'Official',
  'announcements.published': 'Published',

  // --- assets ------------------------------------------------------------------
  'assets.assigned_assets': 'Assigned Assets',
  'assets.company_assets_issued_to_you_laptop': 'Company assets issued to you: laptop, mobile, SIM, bag, ID card and samples, with their return condition.',
  'assets.issued': 'Issued',
  'assets.returned': 'Returned',
  'assets.salesman_assets': 'Salesman Assets',

  // --- attendance --------------------------------------------------------------
  'attendance.absent': 'Absent',
  'attendance.attendance_sheet': 'Attendance Sheet',
  'attendance.days': 'Days',
  'attendance.half_day': 'Half day',
  'attendance.hours': '{n} h',
  'attendance.in_out': 'In {in} • Out {out}',
  'attendance.present': 'Present',
  'attendance.this_month': 'This month',
  'attendance.worked': 'Worked',
  'attendance.your_gps_check_in_and_check': 'Your GPS check-in and check-out history for the month, with present, half day and absent days.',

  // --- auth --------------------------------------------------------------------
  'auth.bawaskar_salesman': 'Bawaskar Salesman',
  'auth.enter_a_valid_salesman_email_address': 'Enter a valid salesman email address.',
  'auth.enter_your_password': 'Enter your password.',
  'auth.invalid_email': 'Invalid Email',
  'auth.invalid_login_response': 'Invalid login response.',
  'auth.login': 'Login',
  'auth.login_failed': 'Login Failed',
  'auth.login_token_or_salesman_information_missing': 'Login token or salesman information missing.',
  'auth.password': 'Password',
  'auth.password_required': 'Password Required',
  'auth.salesman_email': 'Salesman email',
  'auth.salesman_erp_login': 'Salesman ERP Login',
  'auth.use_the_salesman_account_created_by': 'Use the Salesman account created by Admin.',

  // --- collections -------------------------------------------------------------
  'collections.amount': 'Amount',
  'collections.amount_required': 'Amount Required',
  'collections.bank_transfer': 'Bank Transfer',
  'collections.cash': 'Cash',
  'collections.cheque': 'Cheque',
  'collections.collect_payment': 'Collect Payment',
  'collections.collection_failed': 'Collection Failed',
  'collections.dealer_required': 'Dealer Required',
  'collections.enter_a_valid_payment_amount': 'Enter a valid payment amount.',
  'collections.enter_amount': 'Enter amount',
  'collections.optional_upi_bank_cheque_reference': 'Optional UPI / bank / cheque reference',
  'collections.payment_collected': 'Payment Collected',
  'collections.payment_collected_receipt': 'Payment collected: {receipt}',
  'collections.payment_collected_successfully': 'Payment collected successfully.',
  'collections.payment_mode': 'Payment Mode',
  'collections.record_a_payment_received_from_an': 'Record a payment received from an assigned dealer.',
  'collections.saving': 'Saving...',
  'collections.select_dealer': 'Select dealer',
  'collections.select_the_dealer_who_made_the': 'Select the dealer who made the payment.',
  'collections.transaction_reference': 'Transaction Reference',
  'collections.upi': 'UPI',

  // --- common ------------------------------------------------------------------
  'common.achieved': 'Achieved',
  'common.advance_and_loan': 'Advance & Loan',
  'common.announcements': 'Announcements',
  'common.approved': 'Approved',
  'common.apr': 'Apr',
  'common.asset': 'Asset',
  'common.assets': 'Assets',
  'common.assigned_dealers': 'Assigned Dealers',
  'common.attendance': 'Attendance',
  'common.aug': 'Aug',
  'common.claimed': 'Claimed',
  'common.collections': 'Collections',
  'common.completed': 'Completed',
  'common.could_not_load': 'Could not load',
  'common.dashboard': 'Dashboard',
  'common.date_range': '{from} to {to}',
  'common.dealer': 'Dealer',
  'common.dealers': 'Dealers',
  'common.dec': 'Dec',
  'common.deductions': 'Deductions',
  'common.delivered': 'Delivered',
  'common.dispatch': 'Dispatch',
  'common.email': 'Email',
  'common.expenses': 'Expenses',
  'common.feb': 'Feb',
  'common.gps': 'GPS',
  'common.help_and_support': 'Help & Support',
  'common.home': 'Home',
  'common.incentives': 'Incentives',
  'common.jan': 'Jan',
  'common.jul': 'Jul',
  'common.jun': 'Jun',
  'common.logout': 'Logout',
  'common.mar': 'Mar',
  'common.may': 'May',
  'common.my_documents': 'My Documents',
  'common.my_profile': 'My Profile',
  'common.my_shift': 'My Shift',
  'common.network_request_failed': 'Network request failed',
  'common.no_gps': 'No GPS',
  'common.nothing_here_yet': 'Nothing here yet',
  'common.notifications': 'Notifications',
  'common.nov': 'Nov',
  'common.oct': 'Oct',
  'common.orders': 'Orders',
  'common.outstanding': 'Outstanding',
  'common.overall': 'Overall',
  'common.payment_collection': 'Payment Collection',
  'common.payslips': 'Payslips',
  'common.pending': 'Pending',
  'common.performance': 'Performance',
  'common.products': 'Products',
  'common.raise_a_support_ticket': 'Raise a support ticket',
  'common.recent_records': 'Recent Records',
  'common.records': 'Records',
  'common.remaining': 'Remaining',
  'common.request_failed': 'Request failed',
  'common.route': 'Route',
  'common.salary': 'Salary',
  'common.sales': 'Sales',
  'common.salesman': 'Salesman',
  'common.sep': 'Sep',
  'common.shift': 'Shift',
  'common.this_action_is_not_available_yet': 'This action is not available yet.',
  'common.this_year': 'This year',
  'common.total': 'Total',
  'common.tour_plan': 'Tour Plan',
  'common.verified': 'Verified',
  'common.visits': 'Visits',

  // --- dashboard ---------------------------------------------------------------
  'dashboard.active_assignment': 'Active assignment',
  'dashboard.catalog': 'Catalog',
  'dashboard.claim': 'Claim',
  'dashboard.collected_today': 'Collected today',
  'dashboard.expense': 'Expense',
  'dashboard.gps': 'GPS',
  'dashboard.hey': 'Hey {name},',
  'dashboard.invalid_dashboard_response': 'Invalid dashboard response.',
  'dashboard.need_review': 'Need review',
  'dashboard.operations': 'Operations',
  'dashboard.pending_orders': 'Pending Orders',
  'dashboard.sales_territory': 'Sales Territory',
  'dashboard.today_collection': 'Today Collection',
  'dashboard.visit': 'Visit',
  'dashboard.welcome_back': 'Welcome Back',

  // --- dealers -----------------------------------------------------------------
  'dealers.admin_has_not_assigned_any_dealer': 'Admin has not assigned any dealer to this salesman yet.',
  'dealers.clear': 'Clear',
  'dealers.credit': 'Credit',
  'dealers.dealer_visit': 'Dealer Visit',
  'dealers.due': 'Due',
  'dealers.no_assigned_dealers': 'No Assigned Dealers',
  'dealers.search_assigned_dealer': 'Search assigned dealer...',

  // --- delivery ----------------------------------------------------------------
  'delivery.delivery': 'Delivery',
  'delivery.dispatches': 'Dispatches',
  'delivery.dispatches_for_your_dealers_with_courier': 'Dispatches for your dealers, with courier, tracking number and delivery state.',
  'delivery.in_transit': 'In transit',

  // --- documents ---------------------------------------------------------------
  'documents.aadhaar_card': 'Aadhaar Card',
  'documents.appointment_letter': 'Appointment Letter',
  'documents.bank_details': 'Bank Details',
  'documents.certificate': 'Certificate',
  'documents.documents': 'Documents',
  'documents.documents_on_file': 'Documents On File',
  'documents.driving_licence': 'Driving Licence',
  'documents.id_card': 'ID Card',
  'documents.identity_bank_and_employment_documents_held': 'Identity, bank and employment documents held by HR, with their verification status.',
  'documents.in_review': 'In review',
  'documents.missing': 'Missing',
  'documents.on_file': 'On file',
  'documents.pan_card': 'PAN Card',

  // --- expenses ----------------------------------------------------------------
  'expenses.add_expense': 'Add Expense',
  'expenses.awaiting': 'Awaiting',
  'expenses.expense_claims': 'Expense Claims',
  'expenses.expense_management': 'Expense Management',
  'expenses.expense_submitted_for_approval': 'Expense submitted for approval.',
  'expenses.reimbursable': 'Reimbursable',
  'expenses.travel_fuel_food_and_other_field': 'Travel, fuel, food and other field expenses, with approval and reimbursement status.',

  // --- holidays ----------------------------------------------------------------
  'holidays.holiday_calendar': 'Holiday Calendar',
  'holidays.holiday_list': 'Holiday List',
  'holidays.national_company_and_festival_holidays_declared': 'National, company and festival holidays declared for this year.',
  'holidays.upcoming': 'Upcoming',

  // --- incentives --------------------------------------------------------------
  'incentives.bonus': 'Bonus',
  'incentives.commission': 'Commission',
  'incentives.incentive_and_commission': 'Incentive & Commission',
  'incentives.monthly_earnings': 'Monthly Earnings',
  'incentives.row': 'Incentive {incentive} • Commission {commission} • Bonus {bonus}',
  'incentives.what_you_earned_beyond_basic_salary': 'What you earned beyond basic salary each month: incentives, commission and bonuses.',

  // --- language ----------------------------------------------------------------
  'language.subtitle': 'Product names and app text will be shown in this language.',
  'language.title': 'Choose your language',
  'language.updating': 'Applying language...',

  // --- leave -------------------------------------------------------------------
  'leave.apply_for_leave': 'Apply for Leave',
  'leave.apply_for_leave_track_approvals_and': 'Apply for leave, track approvals and see how much of each entitlement you have left this year.',
  'leave.leave_application_submitted_for_approval': 'Leave application submitted for approval.',
  'leave.leave_applications': 'Leave Applications',
  'leave.leave_management': 'Leave Management',

  // --- main_shell --------------------------------------------------------------
  'main_shell.apply_and_view_leave': 'Apply and view leave',
  'main_shell.collect': 'Collect',
  'main_shell.commission_and_bonuses': 'Commission and bonuses',
  'main_shell.company_holiday_calendar': 'Company holiday calendar',
  'main_shell.company_issued_assets': 'Company issued assets',
  'main_shell.company_notices_and_circulars': 'Company notices and circulars',
  'main_shell.daily_route_schedule': 'Daily route schedule',
  'main_shell.dealer_price_catalog': 'Dealer price catalog',
  'main_shell.dealer_visits': 'Dealer Visits',
  'main_shell.delivery_tracking': 'Delivery Tracking',
  'main_shell.dispatch_and_delivery': 'Dispatch and delivery',
  'main_shell.employee_code_territory_and_contact': 'Employee code, territory and contact',
  'main_shell.gps_check_in_and_working_hours': 'GPS check in and working hours',
  'main_shell.holidays': 'Holidays',
  'main_shell.identity_and_employment_papers': 'Identity and employment papers',
  'main_shell.kpi_scores_and_reviews': 'KPI scores and reviews',
  'main_shell.leave': 'Leave',
  'main_shell.monthly_performance_targets': 'Monthly performance targets',
  'main_shell.payslip_and_earnings': 'Payslip and earnings',
  'main_shell.refresh': 'Refresh',
  'main_shell.released_monthly_payslips': 'Released monthly payslips',
  'main_shell.request_and_track_recovery': 'Request and track recovery',
  'main_shell.tap_to_view_profile': 'Tap to view profile',
  'main_shell.targets': 'Targets',
  'main_shell.travel_fuel_and_other_claims': 'Travel, fuel and other claims',
  'main_shell.visit_assigned_dealers': 'Visit assigned dealers',
  'main_shell.working_hours_and_weekly_off': 'Working hours and weekly off',

  // --- menu --------------------------------------------------------------------
  'menu.language': 'Language',
  'menu.language_subtitle': 'App language and product names',

  // --- notifications -----------------------------------------------------------
  'notifications.in_inbox': 'In inbox',
  'notifications.inbox': 'Inbox',
  'notifications.mark_all_read': 'Mark all read',
  'notifications.messages': 'Messages',
  'notifications.order_approvals_dispatch_updates_leave_decisions': 'Order approvals, dispatch updates, leave decisions and company notices.',
  'notifications.unread': 'Unread',

  // --- orders ------------------------------------------------------------------
  'orders.admin_review': 'Admin Review',
  'orders.all': 'All',
  'orders.cancelled': 'Cancelled',
  'orders.dealer_orders': 'Dealer Orders',
  'orders.dispatched': 'Dispatched',
  'orders.forward_to_admin': 'Forward to Admin',
  'orders.forwarding': 'Forwarding...',
  'orders.item_count': '{n} items',
  'orders.my_review': 'My Review',
  'orders.no_orders_found': 'No Orders Found',
  'orders.order_forwarded': 'Order Forwarded',
  'orders.orders_from_dealers_assigned_to_you': 'Orders from dealers assigned to you will appear here.',
  'orders.packing': 'Packing',
  'orders.sent_to_admin': '{order} sent to Admin for review.',
  'orders.unable_to_forward': 'Unable to Forward',

  // --- payslips ----------------------------------------------------------------
  'payslips.net_paid': 'Net paid',
  'payslips.payslip_history': 'Payslip History',
  'payslips.your_released_payslips_with_net_pay': 'Your released payslips with net pay, incentives and deductions for each month.',

  // --- performance -------------------------------------------------------------
  'performance.by': 'by {name}',
  'performance.collection': 'Collection',
  'performance.latest': 'Latest',
  'performance.review_history': 'Review History',
  'performance.row': 'Sales {sales} • Collection {collection} • Visits {visits}',
  'performance.score': 'Score',
  'performance.your_kpi_scores_for_sales_collections': 'Your KPI scores for sales, collections and dealer visits, with the reviewer remarks.',

  // --- products ----------------------------------------------------------------
  'products.dealer_price_catalog': 'Dealer Price Catalog',
  'products.dealer_products': 'Dealer Products',
  'products.no_products_available': 'No products available.',
  'products.search_product_sku_category': 'Search product, SKU, category...',

  // --- profile -----------------------------------------------------------------
  'profile.employee_code': 'Employee Code',
  'profile.mobile': 'Mobile',
  'profile.sign_out_from_the_salesman_app': 'Sign out from the salesman app',
  'profile.territory': 'Territory',

  // --- reports -----------------------------------------------------------------
  'reports.achieved_against': 'Achieved {achieved} against {target}',
  'reports.assigned': 'Assigned',
  'reports.assigned_dealers': 'Assigned dealers',
  'reports.awaiting_approval': '{n} awaiting approval',
  'reports.claims_worth': '{n} claims worth {amount}',
  'reports.dealers_currently_mapped_to_your_territory': 'Dealers currently mapped to your territory',
  'reports.expense_claims': 'Expense claims',
  'reports.reports': 'Reports',
  'reports.summary': 'Summary',
  'reports.target_achievement': 'Target achievement',
  'reports.your_field_performance_at_a_glance': 'Your field performance at a glance: dealers, targets, expenses and earnings.',

  // --- salary ------------------------------------------------------------------
  'salary.april': 'April',
  'salary.august': 'August',
  'salary.december': 'December',
  'salary.february': 'February',
  'salary.january': 'January',
  'salary.july': 'July',
  'salary.june': 'June',
  'salary.latest_net': 'Latest net',
  'salary.march': 'March',
  'salary.november': 'November',
  'salary.october': 'October',
  'salary.salary_slips': 'Salary Slips',
  'salary.september': 'September',
  'salary.this_slip': 'This slip',
  'salary.your_salary_structure_monthly_earnings_allowances': 'Your salary structure, monthly earnings, allowances and deductions.',

  // --- shifts ------------------------------------------------------------------
  'shifts.allowed': 'Allowed',
  'shifts.assignment_period': 'Assignment period',
  'shifts.ends': 'Ends',
  'shifts.fri': 'Fri',
  'shifts.grace': 'Grace',
  'shifts.mon': 'Mon',
  'shifts.sat': 'Sat',
  'shifts.shift_details': 'Shift Details',
  'shifts.shift_in': 'Shift in',
  'shifts.shift_out': 'Shift out',
  'shifts.starts': 'Starts',
  'shifts.sun': 'Sun',
  'shifts.thu': 'Thu',
  'shifts.tue': 'Tue',
  'shifts.wed': 'Wed',
  'shifts.weekly_off': 'Weekly off: {days}',
  'shifts.your_working_hours_grace_period_and': 'Your working hours, grace period and weekly offs under the shift you are assigned to.',

  // --- support -----------------------------------------------------------------
  'support.create_ticket': 'Create Ticket',
  'support.enter_subject_and_message': 'Enter subject and message.',
  'support.message': 'Message',
  'support.required': 'Required',
  'support.sending': 'Sending...',
  'support.subject': 'Subject',
  'support.support_failed': 'Support Failed',
  'support.support_sent': 'Support Sent',
  'support.your_support_ticket_has_been_created': 'Your support ticket has been created.',

  // --- targets -----------------------------------------------------------------
  'targets.achieved_of': 'Achieved {done} of {goal}',
  'targets.all_periods': 'All periods',
  'targets.commission_percent': 'Commission {n}%',
  'targets.monthly_and_period_targets_with_achievement': 'Monthly and period targets with achievement, shortfall and the commission rate attached to each.',
  'targets.progress': 'Progress',
  'targets.sales_targets': 'Sales Targets',
  'targets.target': 'Target',
  'targets.target_periods': 'Target Periods',

  // --- tour_plan ---------------------------------------------------------------
  'tour_plan.planned': 'Planned',
  'tour_plan.planned_routes': 'Planned Routes',
  'tour_plan.routes': 'Routes',
  'tour_plan.your_planned_routes_the_dealers_on': 'Your planned routes, the dealers on each and the approval state of the plan.',

  // --- visits ------------------------------------------------------------------
  'visits.daily_visits': 'Daily Visits',
  'visits.dealer_visits_logged_with_gps_location': 'Dealer visits logged with GPS location, purpose and the remarks you captured on site.',
  'visits.gps_tagged': 'GPS tagged',
  'visits.logged': 'Logged',
  'visits.today': 'Today',
  'visits.visit_log': 'Visit Log',
};
